print("\n\n\nit is a little {adjective} to see a worksheet on my thanks giving plate")
print("when there should ne nothing but a triple helping of {food}")
print("but I also realize that this holiday is the only one where we talk about")
print("feeling {feeling} so I wanted to be sure that I took a moment to reflect")
print("on the past year,a year that has been filled with {activity}")
print("and {activity} and probably way too much {favorite activity}!")
print("I could have done without the {noun},and I wish when")
print("I woke up at {number} A.M,that I hadn't worried about {stressful noun}")
print("but there is a lot to celebrate,too.I am still grateful that I still have my {noun}")
print("and I finally had the chance to {verb} (that was so funny,")
print("{person}!) But mostly I am thankful to the people around ")
print("this table,without out whom I most likely to be {adjective}.")
print("\t\t\t\t\tHappy thanks giving")

adjective = input("enter an adjective:")
food = input("enter a food name:")
feeling = input("enter a feeling:")
activity = input("enter an activity:")
activity_2 = input("enter an activity:")
favorite_activity = input("enter an favorite activity:")
noun = input("enter a noun:")
number = input("enter a number:")
stressful_noun = input("enter a stressful noun:")
noun_2 = input("enter a noun:")
verb = input("enter a verb:")
person = input("enter a person name:")
adjective_2 = input("enter an adjective:")

print("\n\n\nit is a little" + "[" + adjective + "]" + "to see a worksheet on my thanks giving plate")
print("when there should ne nothing but a triple helping of " + "[" + food + "]" ".")
print("but I also realize that this holiday is the only one where we talk about")
print("feeling" + "[" + feeling + "]" + ".So I wanted to be sure that I took a moment to reflect")
print("on the past year,a year that has been filled with " + "[" + activity + "]""." )
print("and" + "[" + activity_2 + "]" + "and probably way to much" + "[" + favorite_activity + "]" + "!")
print("I could have done without the" + "[" + noun + "]" + ",and I wish when")
print("I woke up at " + "[" + str(number) + "]" + "A.M,that I hadn't worried about" "[" + stressful_noun + "]" + "." )
print("but there is a lot to celebrate,too.I am still grateful that I still have my" + "[" + noun_2 + "]" )
print("and I finally had the chance to " + "[" + verb + "]" + "(that was so funny,")
print("[" + person + "]!)" + "But mostly I am thankful to the people around ")
print("this table,without out whom I most likely to be." + "[" + adjective_2 + "]" + ".")
print("\t\t\t\t\tHappy thanks giving")

input("do you want to exit")