test_subject = "this is a long string it should be atleast 20 or not if not I am gonna game"
print(len(test_subject))
length_variable = len(test_subject)
print(length_variable)
print(test_subject[0])
print(test_subject[26])
print(test_subject[2])
print(test_subject[6])
print(test_subject[9])
print(test_subject[22])
print(test_subject[40])
print(test_subject[14])
print(test_subject[25])
print(test_subject[36])
print(test_subject[47])
print(test_subject[5])
print(test_subject[49])
print(test_subject[65])
print(test_subject[9])
print(test_subject.index(" string"))